### ISSUE TITLE
Error:  6252 raise KeyError(f"{not_found} not in index")

### ISSUE THREAD

**Issue by yulijia** [SydneyBioX/BIDCell#20]
Hi, I got an error message when running bidcell. It seems there are many unknown gene names, such as "UnassignedCodeword_0069" in the list. However, I am using the xenium data with references provided by this paper.  
Do you have any suggestions on how to locate the problem?

```
Patch H 30000:30678, W 30000:39807
(678, 9807)
Reading filtered transcripts
8.129581 8450.894 6.5879064 6510.0454
Transforming x_location
Transforming y_location
30023 39763 30000 30626
Transforming x_location
Transforming y_location
23 9763 0 626
Extracting cell-gene matrix chunks
/dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
Combining cell-gene matrix chunks
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [03:54<00:00, 26.05s/it]
Obtained cell-gene matrix
Done
Number of cells: 41637
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[5], line 3
      1 # BIDCellModel.get_example_data()
      2 model = BIDCellModel("/users/stgrad/lijiay/Usyd-bidcell_melanoma/xenium_melanoma.yaml")
----> 3 model.run_pipeline()

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/bidcell/BIDCellModel.py:40, in BIDCellModel.run_pipeline(self)
     38 print("### Preprocessing ###")
     39 print()
---> 40 self.preprocess()
     41 print()
     42 print("### Training ###")

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/bidcell/BIDCellModel.py:65, in BIDCellModel.preprocess(self)
     63 generate_patches(self.config)
     64 make_cell_gene_mat(self.config, is_cell=False)
---> 65 preannotate(self.config)

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/bidcell/processing/preannotate.py:98, in preannotate(config)
     96 genes_cells = df_cells.columns[1:].tolist()
     97 ct_columns = df_ref_orig.columns[-3:].tolist()
---> 98 df_ref = df_ref_orig[genes_cells + ct_columns]
    100 genes_ref = df_ref.columns[:-3]
    101 if list(genes_cells) != list(genes_ref):

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/pandas/core/frame.py:4108, in DataFrame.__getitem__(self, key)
   4106     if is_iterator(key):
   4107         key = list(key)
-> 4108     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   4110 # take() does not accept boolean indexers
   4111 if getattr(indexer, "dtype", None) == bool:

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/pandas/core/indexes/base.py:6200, in Index._get_indexer_strict(self, key, axis_name)
   6197 else:
   6198     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 6200 self._raise_if_missing(keyarr, indexer, axis_name)
   6202 keyarr = self.take(indexer)
   6203 if isinstance(key, Index):
   6204     # GH 42790 - Preserve name from an Index

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/pandas/core/indexes/base.py:6252, in Index._raise_if_missing(self, key, indexer, axis_name)
   6249     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   6251 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 6252 raise KeyError(f"{not_found} not in index")

KeyError: "['ABCC11', 'ACE2', 'ACKR1', 'ACTG2', 'ADAM28', 'ADAMTS1', 'ADGRE1', 'ADGRL4', 'ADH1C', 'ADH4', 'ADIPOQ', 'AGER', 'AGR3', 'AHSP', 'AIF1', 'ALAS2', 'ALDH1A3', 'AMY2A', 'ANPEP', 'APCDD1', 'APOA5', 'APOBEC3A', 'APOLD1', 'AQP2', 'AQP3', 'AQP8', 'AQP9', 'AR', 'ARFGEF3', 'ASCL1', 'ASCL3', 'ASPN', 'BAMBI', 'BANK1', 'BASP1', 'BBOX1', 'BCL2L11', 'BMX', 'BTNL9', 'C1orf162', 'C1orf194', 'C5orf46', 'C6orf118', 'C7', 'C15orf48', 'C20orf85', 'CA4', 'CAPN8', 'CAVIN1', 'CAVIN2', 'CCDC39', 'CCDC78', 'CCL19', 'CCL27', 'CCNB2', 'CD1A', 'CD5L', 'CD34', 'CD69', 'CD93', 'CD247', 'CD300E', 'CDH16', 'CDK1', 'CENPF', 'CFAP53', 'CFB', 'CFHR1', 'CFHR3', 'CFTR', 'CHGA', 'CLCA2', 'CLEC4E', 'CLEC10A', 'CLECL1', 'CLIC6', 'CNN1', 'COCH', 'COL5A2', 'COL17A1', 'CPA3', 'CRHBP', 'CRISPLD2', 'CTSK', 'CXCL6', 'CYP1A1', 'CYP2A7', 'CYP2B6', 'CYP2F1', 'CYP3A4', 'CYP4B1', 'CYTIP', 'DIRAS3', 'DMBT1', 'DNAAF1', 'DNASE1L3', 'DPEP1', 'DPT', 'DST', 'DUSP2', 'ECSCR', 'EDN1', 'EDNRB', 'EGFL7', 'EHF', 'ELF5', 'ERG', 'ESR1', 'FAS', 'FBN1', 'FCGR1A', 'FCN1', 'FCN2', 'FGFBP1', 'FGL2', 'FHL2', 'FKBP11', 'FOXA1', 'FOXI1', 'FOXJ1', 'FSTL3', 'FXYD2', 'GATA2', 'GATM', 'GCG', 'GDF15', 'GEM', 'GHRL', 'GKN2', 'GLIPR1', 'GLYATL1', 'GNG11', 'GPC1', 'GPC3', 'GPR183', 'GPRC5A', 'GPX2', 'GYPA', 'GYPB', 'HAMP', 'HEMGN', 'HEPACAM2', 'HES4', 'HIGD1B', 'HLA-DQB2', 'HMGCS2', 'HPGDS', 'HPX', 'IGSF6', 'IL1RL1', 'IL7R', 'INMT', 'INS', 'IRF8', 'KCNK3', 'KCNMA1', 'KLK11', 'KLRD1', 'KNG1', 'KRT7', 'KRT20', 'LGI4', 'LIF', 'LILRA4', 'LILRA5', 'LILRB2', 'LILRB4', 'LPL', 'LTBP2', 'LY6D', 'LY86', 'LYVE1', 'MALL', 'MAMDC2', 'MCEMP1', 'MCF2L', 'MDM2', 'MEDAG', 'MEF2C', 'MEST', 'MLANA', 'MLPH', 'MNDA', 'MPEG1', 'MS4A2', 'MS4A4A', 'MS4A6A', 'MTRNR2L11', 'MYBPC1', 'MYLK', 'NAT8', 'NPDC1', 'NTN4', 'OGN', 'OPRPN', 'PCOLCE', 'PCP4', 'PCSK2', 'PEBP4', 'PGR', 'PLA2G7', 'PLAC9', 'PLCG2', 'PLD4', 'PLIN4', 'PMP22', 'PPARG', 'PPP1R1A', 'PPP1R1B', 'PPY', 'PRDM1', 'PRG4', 'PTGDS', 'PTN', 'PVALB', 'RAMP2', 'RAPGEF3', 'RBP5', 'RERGL', 'RETN', 'RGS16', 'RIDA', 'RND1', 'RTKN2', 'S100A1', 'S100A12', 'SCGB2A1', 'SCGN', 'SELE', 'SEMA3C', 'SERPINB2', 'SERPINB3', 'SERPINB9', 'SFRP4', 'SFTA2', 'SH2D3C', 'SLAMF1', 'SLAMF7', 'SLC4A1', 'SLC18A2', 'SLC22A8', 'SLC26A2', 'SMIM24', 'SMYD2', 'SNCA', 'SNCG', 'SNTN', 'SOX17', 'SOX18', 'SPDEF', 'SPI1', 'SPIB', 'SRPX', 'SST', 'STC1', 'STC2', 'STEAP4', 'TAC1', 'TAT', 'TCF4', 'TCF15', 'TCIM', 'TENT5C', 'TFF2', 'TFPI', 'THAP2', 'THBS2', 'THY1', 'TIMP4', 'TM4SF4', 'TM4SF18', 'TMC5', 'TMEM52B', 'TMEM100', 'TMEM174', 'TOP2A', 'TSPAN19', 'UBE2C', 'UMOD', 'UPK3B', 'UnassignedCodeword_0006', 'UnassignedCodeword_0037', 'UnassignedCodeword_0069', 'UnassignedCodeword_0400', 'UnassignedCodeword_0401', 'UnassignedCodeword_0402', 'UnassignedCodeword_0406', 'UnassignedCodeword_0407', 'UnassignedCodeword_0409', 'UnassignedCodeword_0410', 'UnassignedCodeword_0413', 'UnassignedCodeword_0415', 'UnassignedCodeword_0416', 'UnassignedCodeword_0417', 'UnassignedCodeword_0418', 'UnassignedCodeword_0421', 'UnassignedCodeword_0422', 'UnassignedCodeword_0423', 'UnassignedCodeword_0424', 'UnassignedCodeword_0425', 'UnassignedCodeword_0426', 'UnassignedCodeword_0427', 'UnassignedCodeword_0428', 'UnassignedCodeword_0429', 'UnassignedCodeword_0430', 'UnassignedCodeword_0431', 'UnassignedCodeword_0432', 'UnassignedCodeword_0433', 'UnassignedCodeword_0434', 'UnassignedCodeword_0435', 'UnassignedCodeword_0437', 'UnassignedCodeword_0438', 'UnassignedCodeword_0439', 'UnassignedCodeword_0440', 'UnassignedCodeword_0441', 'UnassignedCodeword_0442', 'UnassignedCodeword_0443', 'UnassignedCodeword_0444', 'UnassignedCodeword_0445', 'UnassignedCodeword_0446', 'UnassignedCodeword_0447', 'UnassignedCodeword_0448', 'UnassignedCodeword_0449', 'UnassignedCodeword_0451', 'UnassignedCodeword_0453', 'UnassignedCodeword_0455', 'UnassignedCodeword_0457', 'UnassignedCodeword_0458', 'UnassignedCodeword_0460', 'UnassignedCodeword_0461', 'UnassignedCodeword_0462', 'UnassignedCodeword_0463', 'UnassignedCodeword_0464', 'UnassignedCodeword_0465', 'UnassignedCodeword_0466', 'UnassignedCodeword_0467', 'UnassignedCodeword_0468', 'UnassignedCodeword_0469', 'UnassignedCodeword_0470', 'UnassignedCodeword_0471', 'UnassignedCodeword_0472', 'UnassignedCodeword_0473', 'UnassignedCodeword_0475', 'UnassignedCodeword_0476', 'UnassignedCodeword_0478', 'UnassignedCodeword_0479', 'UnassignedCodeword_0480', 'UnassignedCodeword_0482', 'UnassignedCodeword_0484', 'UnassignedCodeword_0485', 'UnassignedCodeword_0487', 'UnassignedCodeword_0488', 'UnassignedCodeword_0489', 'UnassignedCodeword_0490', 'UnassignedCodeword_0491', 'UnassignedCodeword_0492', 'UnassignedCodeword_0494', 'UnassignedCodeword_0495', 'UnassignedCodeword_0496', 'UnassignedCodeword_0497', 'UnassignedCodeword_0498', 'UnassignedCodeword_0499', 'VCAN', 'VSIG4', 'VWA5A'] not in index"
```

Here is my xenium transcripts file
```
"transcript_id","cell_id","overlaps_nucleus","feature_name","x_location","y_location","z_location","qv","fov_name","nucleus_distance"
281801394225157,"UNASSIGNED",0,"FAS",64.4317,4411.439,10.974703,39.912323,"G3",803.2383
281801394225177,"UNASSIGNED",0,"DST",233.44911,4375.053,11.03392,4.9835153,"G3",647.74023
281801394225193,"UNASSIGNED",0,"EDN1",218.87114,4498.7876,11.1449175,9.427272,"G3",666.286
281801394225194,"UNASSIGNED",0,"EDN1",247.96579,4447.5156,10.965405,39.912323,"G3",632.7945
281801394225221,"UNASSIGNED",0,"CTSK",37.158665,4374.042,10.940763,39.912323,"G3",843.79364
281801394225229,"UNASSIGNED",0,"S100A1",228.96375,4454.0537,10.982909,39.912323,"G3",652.1247
281801394225246,"UNASSIGNED",0,"MKI67",169.96713,4410.1924,11.016546,39.912323,"G3",710.011
281801394225262,"UNASSIGNED",0,"IL7R",183.61256,4410.7397,11.006925,39.912323,"G3",696.3624
281801394225263,"UNASSIGNED",0,"SOX17",198.23975,4497.8774,11.341496,9.535972,"G3",686.6519
281801394225279,"UNASSIGNED",0,"UnassignedCodeword_0479",61.861126,4409.3354,11.073855,8.237845,"G3",805.664
281801394225288,"UNASSIGNED",0,"TCL1A",45.18934,4452.1006,11.300056,12.870164,"G3",765.8409
281801394225289,"UNASSIGNED",0,"CTSK",146.76706,4458.1807,11.052568,39.912323,"G3",734.4222
281801394225297,"UNASSIGNED",0,"CLEC4E",110.082054,4346.2627,11.003842,9.651478,"G3",772.9341
281801394225299,"UNASSIGNED",0,"MLPH",173.52837,4363.237,10.904587,39.912323,"G3",708.32074
281801394225308,"UNASSIGNED",0,"EDNRB",97.10216,4422.878,10.993612,39.912323,"G3",782.8928
281801394225311,"UNASSIGNED",0,"TNC",246.31725,4481.4067,11.089268,8.800486,"G3",637.0378
281801394225334,"UNASSIGNED",0,"CD1A",229.67227,4491.2266,11.115642,39.912323,"G3",654.65576
281801394225354,"UNASSIGNED",0,"CD4",45.094402,4452.2144,11.343499,31.753756,"G3",765.74414
281801394225365,"UNASSIGNED",0,"CYTIP",248.69576,4460.3647,11.021127,11.029679,"G3",632.8414
281801394225152,"UNASSIGNED",0,"MLANA",33.617447,4556.833,11.255369,39.912323,"G3",664.9957
281801394225153,"UNASSIGNED",0,"MLANA",33.91641,4557.5996,11.174727,22.09146,"G3",664.1842
281801394225167,"UNASSIGNED",0,"BANK1",34.538055,4533.9507,11.163204,11.175613,"G3",687.22736
281801394225168,"UNASSIGNED",0,"CD3D",155.16702,4541.9004,11.33819,20.019194,"G3",665.99786
281801394225173,"UNASSIGNED",0,"CD86",29.723776,4739.4316,11.347541,26.285347,"G3",488.80313
281801394225180,"UNASSIGNED",0,"LILRA4",84.95069,4665.93,11.295444,9.629819,"G3",548.4093
281801394225181,"UNASSIGNED",0,"LILRA4",175.66214,4709.5605,11.304475,33.315056,"G3",498.20258
281801394225187,"UNASSIGNED",0,"KLRB1",188.06314,4511.1763,11.1515875,39.912323,"G3",696.7795
281801394225192,"UNASSIGNED",0,"EDN1",8.820337,4676.1,11.326466,33.620106,"G3",555.4719
281801394225213,"UNASSIGNED",0,"UnassignedCodeword_0461",63.145008,4613.9604,11.191236,10.264473,"G3",603.27783
281801394225214,"UNASSIGNED",0,"UnassignedCodeword_0461",117.42014,4621.4624,11.339442,10.264473,"G3",588.60956
281801394225238,"UNASSIGNED",0,"KCNMA1",148.0342,4672.2256,11.282919,11.828474,"G3",535.95386
281801394225249,"UNASSIGNED",0,"AQP3",78.21362,4718.8774,11.599309,9.574088,"G3",497.36328
281801394225253,"UNASSIGNED",0,"S100A1",107.41762,4504.1113,11.033251,39.912323,"G3",706.3853
281801394225254,"UNASSIGNED",0,"S100A1",133.8964,4557.1304,11.217244,39.912323,"G3",651.5967
```

**Comment by yulijia** [comment]
After recreate reference and marker files. I still encounter the same error.

> 'UnassignedCodeword_*' not in index

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[6], line 3
      1 # BIDCellModel.get_example_data()
      2 model = BIDCellModel("./xenium_melanoma.yaml")
----> 3 model.run_pipeline()

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/bidcell/BIDCellModel.py:40, in BIDCellModel.run_pipeline(self)
     38 print("### Preprocessing ###")
     39 print()
---> 40 self.preprocess()
     41 print()
     42 print("### Training ###")

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/bidcell/BIDCellModel.py:65, in BIDCellModel.preprocess(self)
     63 generate_patches(self.config)
     64 make_cell_gene_mat(self.config, is_cell=False)
---> 65 preannotate(self.config)

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/bidcell/processing/preannotate.py:98, in preannotate(config)
     96 genes_cells = df_cells.columns[1:].tolist()
     97 ct_columns = df_ref_orig.columns[-3:].tolist()
---> 98 df_ref = df_ref_orig[genes_cells + ct_columns]
    100 genes_ref = df_ref.columns[:-3]
    101 if list(genes_cells) != list(genes_ref):

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/pandas/core/frame.py:4108, in DataFrame.__getitem__(self, key)
   4106     if is_iterator(key):
   4107         key = list(key)
-> 4108     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   4110 # take() does not accept boolean indexers
   4111 if getattr(indexer, "dtype", None) == bool:

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/pandas/core/indexes/base.py:6200, in Index._get_indexer_strict(self, key, axis_name)
   6197 else:
   6198     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 6200 self._raise_if_missing(keyarr, indexer, axis_name)
   6202 keyarr = self.take(indexer)
   6203 if isinstance(key, Index):
   6204     # GH 42790 - Preserve name from an Index

File /dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/pandas/core/indexes/base.py:6252, in Index._raise_if_missing(self, key, indexer, axis_name)
   6249     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   6251 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 6252 raise KeyError(f"{not_found} not in index")

KeyError: "['UnassignedCodeword_0006', 'UnassignedCodeword_0037', 'UnassignedCodeword_0069', 'UnassignedCodeword_0400', 'UnassignedCodeword_0401', 'UnassignedCodeword_0402', 'UnassignedCodeword_0403', 'UnassignedCodeword_0404', 'UnassignedCodeword_0405', 'UnassignedCodeword_0406', 'UnassignedCodeword_0407', 'UnassignedCodeword_0408', 'UnassignedCodeword_0409', 'UnassignedCodeword_0411', 'UnassignedCodeword_0412', 'UnassignedCodeword_0413', 'UnassignedCodeword_0414', 'UnassignedCodeword_0415', 'UnassignedCodeword_0416', 'UnassignedCodeword_0417', 'UnassignedCodeword_0419', 'UnassignedCodeword_0420', 'UnassignedCodeword_0421', 'UnassignedCodeword_0424', 'UnassignedCodeword_0425', 'UnassignedCodeword_0427', 'UnassignedCodeword_0428', 'UnassignedCodeword_0429', 'UnassignedCodeword_0430', 'UnassignedCodeword_0431', 'UnassignedCodeword_0432', 'UnassignedCodeword_0433', 'UnassignedCodeword_0434', 'UnassignedCodeword_0435', 'UnassignedCodeword_0436', 'UnassignedCodeword_0437', 'UnassignedCodeword_0438', 'UnassignedCodeword_0439', 'UnassignedCodeword_0440', 'UnassignedCodeword_0442', 'UnassignedCodeword_0443', 'UnassignedCodeword_0444', 'UnassignedCodeword_0445', 'UnassignedCodeword_0446', 'UnassignedCodeword_0447', 'UnassignedCodeword_0448', 'UnassignedCodeword_0449', 'UnassignedCodeword_0450', 'UnassignedCodeword_0451', 'UnassignedCodeword_0452', 'UnassignedCodeword_0453', 'UnassignedCodeword_0454', 'UnassignedCodeword_0456', 'UnassignedCodeword_0457', 'UnassignedCodeword_0458', 'UnassignedCodeword_0459', 'UnassignedCodeword_0460', 'UnassignedCodeword_0461', 'UnassignedCodeword_0462', 'UnassignedCodeword_0463', 'UnassignedCodeword_0464', 'UnassignedCodeword_0465', 'UnassignedCodeword_0468', 'UnassignedCodeword_0470', 'UnassignedCodeword_0471', 'UnassignedCodeword_0472', 'UnassignedCodeword_0473', 'UnassignedCodeword_0474', 'UnassignedCodeword_0475', 'UnassignedCodeword_0476', 'UnassignedCodeword_0477', 'UnassignedCodeword_0478', 'UnassignedCodeword_0479', 'UnassignedCodeword_0481', 'UnassignedCodeword_0482', 'UnassignedCodeword_0483', 'UnassignedCodeword_0484', 'UnassignedCodeword_0485', 'UnassignedCodeword_0488', 'UnassignedCodeword_0489', 'UnassignedCodeword_0490', 'UnassignedCodeword_0492', 'UnassignedCodeword_0493', 'UnassignedCodeword_0494', 'UnassignedCodeword_0495', 'UnassignedCodeword_0497', 'UnassignedCodeword_0498', 'UnassignedCodeword_0499'] not in index"
```

**Comment by yulijia** [comment]
https://github.com/SydneyBioX/BIDCell/blob/e565988cd2e78e622c68bd0a5649a1ec8b9b281f/bidcell/processing/cell_gene_matrix.py#L164


I found the reason: each time the model needs to run in a new folder. Otherwise, this command will skip the processing steps and use the old results.

**Comment by yulijia** [comment]
I don't understand. I used exactly the same genes in the reference and panel, but I still received this error message when processing a sample.


```
Obtained cell-gene matrix
Done
Number of cells: 47676
Traceback (most recent call last):
  File "/dskh/nobackup/lijiay/Usyd-bidcell_melanoma/20240722-run_melanoma_example-LY/src/02-run_pipeline.py", line 46, in <module>
    model.run_pipeline()
  File "/dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/bidcell/BIDCellModel.py", line 40, in run_pipeline
    self.preprocess()
  File "/dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/bidcell/BIDCellModel.py", line 65, in preprocess
    preannotate(self.config)
  File "/dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/bidcell/processing/preannotate.py", line 98, in preannotate
    df_ref = df_ref_orig[genes_cells + ct_columns]
  File "/dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/dskh/nobackup/lijiay/miniconda3/envs/bidcell/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['ABCC11', 'ACE2', 'ACKR1', 'ACTG2', 'ADAM28', 'ADAMTS1', 'ADGRE1', 'ADGRL4', 'ADH1C', 'ADH4', 'ADIPOQ', 'AGER', 'AGR3', 'AHSP', 'AIF1', 'ALAS2', 'ALDH1A3', 'AMY2A', 'ANPEP', 'APCDD1', 'APOA5', 'APOBEC3A', 'APOLD1', 'AQP2', 'AQP3', 'AQP8', 'AQP9', 'AR', 'ARFGEF3', 'ASCL1', 'ASCL3', 'ASPN', 'BAMBI', 'BANK1', 'BASP1', 'BBOX1', 'BCL2L11', 'BMX', 'BTNL9', 'C1orf162', 'C1orf194', 'C5orf46', 'C6orf118', 'C7', 'C15orf48', 'C20orf85', 'CA4', 'CAPN8', 'CAVIN1', 'CAVIN2', 'CCDC39', 'CCDC78', 'CCL19', 'CCL27', 'CCNB2', 'CD1A', 'CD5L', 'CD34', 'CD69', 'CD93', 'CD247', 'CD300E', 'CDH16', 'CDK1', 'CENPF', 'CFAP53', 'CFB', 'CFHR1', 'CFHR3', 'CFTR', 'CHGA', 'CLCA2', 'CLEC4E', 'CLEC10A', 'CLECL1', 'CLIC6', 'CNN1', 'COCH', 'COL5A2', 'COL17A1', 'CPA3', 'CRHBP', 'CRISPLD2', 'CTSK', 'CXCL6', 'CYP1A1', 'CYP2A7', 'CYP2B6', 'CYP2F1', 'CYP3A4', 'CYP4B1', 'CYTIP', 'DIRAS3', 'DMBT1', 'DNAAF1', 'DNASE1L3', 'DPEP1', 'DPT', 'DST', 'DUSP2', 'ECSCR', 'EDN1', 'EDNRB', 'EGFL7', 'EHF', 'ELF5', 'ERG', 'ESR1', 'FAS', 'FBN1', 'FCGR1A', 'FCN1', 'FCN2', 'FGFBP1', 'FGL2', 'FHL2', 'FKBP11', 'FOXA1', 'FOXI1', 'FOXJ1', 'FSTL3', 'FXYD2', 'GATA2', 'GATM', 'GCG', 'GDF15', 'GEM', 'GHRL', 'GKN2', 'GLIPR1', 'GLYATL1', 'GNG11', 'GPC1', 'GPC3', 'GPR183', 'GPRC5A', 'GPX2', 'GYPA', 'GYPB', 'HAMP', 'HEMGN', 'HEPACAM2', 'HES4', 'HIGD1B', 'HLA-DQB2', 'HMGCS2', 'HPGDS', 'HPX', 'IGSF6', 'IL1RL1', 'IL7R', 'INMT', 'INS', 'IRF8', 'KCNK3', 'KCNMA1', 'KLK11', 'KLRD1', 'KNG1', 'KRT7', 'KRT20', 'LGI4', 'LIF', 'LILRA4', 'LILRA5', 'LILRB2', 'LILRB4', 'LPL', 'LTBP2', 'LY6D', 'LY86', 'LYVE1', 'MALL', 'MAMDC2', 'MCEMP1', 'MCF2L', 'MDM2', 'MEDAG', 'MEF2C', 'MEST', 'MLANA', 'MLPH', 'MNDA', 'MPEG1', 'MS4A2', 'MS4A4A', 'MS4A6A', 'MTRNR2L11', 'MYBPC1', 'MYLK', 'NAT8', 'NPDC1', 'NTN4', 'OGN', 'OPRPN', 'PCOLCE', 'PCP4', 'PCSK2', 'PEBP4', 'PGR', 'PLA2G7', 'PLAC9', 'PLCG2', 'PLD4', 'PLIN4', 'PMP22', 'PPARG', 'PPP1R1A', 'PPP1R1B', 'PPY', 'PRDM1', 'PRG4', 'PTGDS', 'PTN', 'PVALB', 'RAMP2', 'RAPGEF3', 'RBP5', 'RERGL', 'RETN', 'RGS16', 'RIDA', 'RND1', 'RTKN2', 'S100A1', 'S100A12', 'SCGB2A1', 'SCGN', 'SELE', 'SEMA3C', 'SERPINB2', 'SERPINB3', 'SERPINB9', 'SFRP4', 'SFTA2', 'SH2D3C', 'SLAMF1', 'SLAMF7', 'SLC4A1', 'SLC18A2', 'SLC22A8', 'SLC26A2', 'SMIM24', 'SMYD2', 'SNCA', 'SNCG', 'SNTN', 'SOX17', 'SOX18', 'SPDEF', 'SPI1', 'SPIB', 'SRPX', 'SST', 'STC1', 'STC2', 'STEAP4', 'TAC1', 'TAT', 'TCF4', 'TCF15', 'TCIM', 'TENT5C', 'TFF2', 'TFPI', 'THAP2', 'THBS2', 'THY1', 'TIMP4', 'TM4SF4', 'TM4SF18', 'TMC5', 'TMEM52B', 'TMEM100', 'TMEM174', 'TOP2A', 'TSPAN19', 'UBE2C', 'UMOD', 'UPK3B', 'VCAN', 'VSIG4', 'VWA5A'] not in index"
```

**Comment by yulijia** [comment]
all solved.
